spring:
    application:
    name: eureka-server


server:
  port: 8761 #Default Eureka port


eureka:
  client:
    register-with-eureka: false  # Server khud register nahi hoga
    fetch-registry: false  # Server ko registry fetch nahi karna



  instance:
    hostname: localhost